
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto

# Transform numbers:
# "If you want to rotate a monitor, add a , transform, X at the end of the monitor rule, where X corresponds to a transform number."
# 0 -> normal (no transforms)
# 1 -> 90 degrees
# 2 -> 180 degrees
# 3 -> 270 degrees
# 4 -> flipped
# 5 -> flipped + 90 degrees
# 6 -> flipped + 180 degrees
# 7 -> flipped + 270 degrees


monitorv2 {
    output = eDP-1
    mode = 1920x1080@60.05600
    position = 0x0
    scale = 1
    transform = 0
}

monitorv2 {
    output = desc:ASUSTek COMPUTER INC ASUS VP249 L5LMTF018764
    mode = 1920x1080@60
    position = -1920x0
    scale = 1
    transform = 0
}

monitorv2 {
    output = desc:ASUSTek COMPUTER INC ASUS VP249 L5LMTF018767
    mode = 1920x1080@60
    position = 1920x-540
    scale = 1
    transform = 3
}

# Auto place unspecified monitors up
monitor = , preferred, auto-center-up, 1


# Old dock
#monitor = DP-1,1920x1080@60,-1920x0,1
#monitor = HDMI-A-1,1920x1080@60,-3840x0,1